server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        enabled: true # 重新启用Nacos服务发现
        server-addr: nacos.io:8848 # 使用公网测试Nacos服务器
        username: nacos
        password: nacos
        namespace: public # 使用public命名空间
    gateway:
      discovery:
        locator:
          enabled: true # 启用基于服务发现的路由功能
          lower-case-service-id: true
      routes:
        - id: user_service_route
          uri: lb://user-service # 负载均衡路由
          predicates:
            - Path=/api/users/**
        - id: qa_service_route
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/**

# 日志配置
logging:
  level:
    com.alibaba.cloud: INFO
    com.alibaba.nacos: INFO
