server:
  port: 8080

spring:
  application:
    name: api-gateway-zj
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_service_route
          uri: lb://user-service-zj
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: qa_service_route1
          uri: lb://qa-service-zj
          predicates:
            - Path=/api/qa/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: false
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
    loadbalancer:
      retry:
        enabled: true
      health-check:
        initial-delay: 0

# 日志配置
logging:
  level:
    com.alibaba.cloud: INFO
    com.alibaba.nacos: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG
