version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ai-qa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ai_qa_system
      MYSQL_USER: aiqa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend-services/qa-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ai-qa-network

  # Nacos Service Discovery
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: ai-qa-nacos
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_devtest
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: password
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    networks:
      - ai-qa-network

  # API Gateway
  api-gateway:
    build:
      context: ./backend-services/api-gateway
      dockerfile: Dockerfile
    container_name: ai-qa-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
    depends_on:
      - nacos
    networks:
      - ai-qa-network

  # User Service
  user-service:
    build:
      context: ./backend-services/user-service
      dockerfile: Dockerfile
    container_name: ai-qa-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
      - nacos
    networks:
      - ai-qa-network

  # QA Service
  qa-service:
    build:
      context: ./backend-services/qa-service
      dockerfile: Dockerfile
    container_name: ai-qa-qa-service
    ports:
      - "8082:8082"
    environment:
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      AI_MODEL_API_KEY: ${AI_API_KEY:-your-api-key-here}
    depends_on:
      - mysql
      - nacos
    networks:
      - ai-qa-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-qa-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - api-gateway
    networks:
      - ai-qa-network

networks:
  ai-qa-network:
    driver: bridge

volumes:
  mysql_data: