server:
  port: 8081

spring:
  application:
    name: user-service-zj

  # MySQL 数据库配置
  datasource:
    url: jdbc:mysql://mysql3.sqlpub.com:3308/airline_order_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: airline_lhy
    password: JxC55d1F7NBBl7aO
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # 启用Nacos服务注册发现
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public

# JWT配置
jwt:
  secret: mySecretKeyForAiQaSystemMustBe256BitsLongForSecurityPurposes
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    com.ai.qa.user: DEBUG
    com.alibaba.cloud: INFO
    com.alibaba.nacos: INFO
